#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start