#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Create a custom HTTP response header
sudo sed -i '/server_name _;/a \
        location /redirect_me {\n\
                rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\
        }' /etc/nginx/sites-available/default

sudo service nginx restart
