#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sudo sed -i '/server_name _;/a \
        location /redirect_me {\n\
                rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\
        }' /etc/nginx/sites-available/default
# Create a custom HTTP response header
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404-not_found.html

# configure nginx to serve a custom page 404-not_found.html when a request is made for a page that doesn’t exist
sudo sed -i '/server_name _;/a \
        error_page 404 /404-not_found.html;\n\
        location = /404-not_found.html {\n\
                root /var/www/html;\n\
                internal;\n\
        }' /etc/nginx/sites-available/default

sudo service nginx restart