#!/usr/bin/env bash
# Dsplay FizzBuzz but number btwn 1 and 100

number=1
while (( number < 101 )); do
	if (( number % 15 == 0 ));
	then
		echo "FizzBuzz"
	elif (( number % 5 == 0 ));
	then
		echo "Buzz"
	elif (( number % 3 == 0 ));
	then
		echo "Fizz"
	else
		echo "$number"
	fi
	(( number++ ))
done