#!/usr/bin/env bash
# Display surprise message on 4th and 8th else Best School

count=1
while [[  $count -lt 11  ]]; do
	if [[  $count = 4  ]]; then
		echo "bad luck"
	elif [[  $count = 8  ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done