#!/usr/bin/env bash
# Display time.

hours=0
while [[  $hours -lt 13  ]]; do
	echo "Hour: $hours"
	minutes=1
	while [[  $minutes -lt 60  ]]; do
		echo $minutes
		(( minutes++))
	done
	(( hours++ ))
done