#!/usr/bin/env bash
#script that uses ssh to connect to your server using the private keyscript that uses ssh to connect to your server using the private key

ssh -i ~/.ssh/school ubuntu@18.234.249.64